[package]
name = "vpop-cli"
description = "Command to read/write version numbers from/to formatted text."
authors = { workspace = true }
version = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "vpop"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
toml_edit = { workspace = true }
vpop = { workspace = true }

[dev-dependencies]
assert_cmd = "2.0.17"
