[package]
name = "vup-cli"
description = "Command line tool to bump version numbers."
authors.workspace = true
version.workspace = true
edition.workspace = true

[[bin]]
name = "vup"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.50", features = ["derive"] }
env_logger = "0.11.8"
log.workspace = true
thiserror.workspace = true
vup.workspace = true

[dev-dependencies]
assert_cmd = "2.0.17"
